### ISSUE TITLE
与 next 主题一起使用时有 css 冲突

### ISSUE THREAD

**Issue by stkwill** [Sukwants/hexo-content-blocks#4]
next 主题中有 css ：

```css
.content {
    padding-top: 40px;
}
```

这导致使用 `contentbox` 时，选择区上下有两个 `padding-top: 40px;` ，非常难看

目前个人的解决方案是在 `index.js` 的 css 区中添加

```css
.cards {
  padding-top: 0px;
}
```

并将 `div.content.cards *` 块中添加 `padding-top: 0px;` 使其成为

```css
div.content.cards * {
  padding-top: 0px;
  box-sizing: border-box;
}
```

分别对应于选择区上下两部分的修复

**Comment by stkwill** [comment]
发现 css 部分与 next 主题的 note 部分也有冲突

next css 中有

```css
.post-body .note p:last-child,
.post-body .note ul:last-child,
.post-body .note ol:last-child,
.post-body .note table:last-child,
.post-body .note pre:last-child,
.post-body .note blockquote:last-child,
.post-body .note img:last-child {
  margin-bottom: 0;
}
```

会导致 box 框内最后一个元素 `margin-bottom` 为 0，下方没有留空

建议修改一下 css 命名规则，把容易冲突的名字如 `note` 改成类似于 `hcb-note` 这种名字
